### Education

I graduated magna cum laude from [The University of Georgia](https://www.terry.uga.edu/) with a BBA in Finance in May 2018. I studied Chemistry for my first two years at The University of Georgia and tutored general chemistry and organic chemistry during that time. I enrolled in the Master of Science, Biostatistics program at the Columbia University Mailman School of Public Health in 2021.
<br>
<br>

### Professional

From August 2018 through July 2021, I worked as an Internal Audit and Financial Advisory Consultant at [Protiviti, Inc.](https://www.protiviti.com/) in the Los Angeles area. This work was project-based with teams from two or three to ten or more members. Projects ranged from entity-level risk assessments with the goal of quantifying relative risk of fraud or loss in various business sectors to performing specific business process audits, such as loan underwriting or financial derivatives management. I gained valuable experience working with diverse teams on a variety of projects in industries including: residential and commercial real estate, community and corporate banking, and clinical stage biopharmaceuticals.
<br>
<br>

### Projects

For an end-of-semester group project in our Data Science course, my group members and I analyzed COVID-19 outcomes data in New York City alongside demographic and socioeconomic data from the U.S. Census. The project, NYC COVID Trends, has its own website [here](https://zacharykatz1.github.io/nyc_covid_trends/index.html).

In an advanced statistical computing course, our group conducted a simulation study to examine the performance of simple and complex bootstrapping methods in estimating standard errors. Specifically, we looked at this question in the context of propensity-score matching. The project report can be found [here](https://github.com/tucker-l-morgan/p8160_proj1_4_C/blob/main/p8160_proj1_report.pdf).